trigger:
  branches:
    include:
      - main

pool:
  name: MySelfHostedAgents

steps:
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | pom.xml'
      path: '$(System.DefaultWorkingDirectory)/.m2/repository'
      cacheHitVar: 'CACHE_HIT'
      displayName: 'Cache Maven dependencies'

  - task: UseJavaVersion@0
    inputs:
      versionSpec: '17'
      architecture: 'x64'

  - script: |
      ./mvnw clean install -B
    displayName: 'Build Spring Boot application'

  - script: |
      ./mvnw test -B
    displayName: 'Run tests'

  - task: PublishBuildArtifacts@0
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/target'
      artifactName: 'spring-boot-app'
      publishLocation: 'Container'
