trigger:
  branches:
    include:
      - main  # Adjust branch name as per your main branch

pool:
  vmImage: 'ubuntu-latest'
  pool:
    name: MySelfHostedAgents


steps:
  - task: UseJavaVersion@0
    inputs:
      versionSpec: '17'  # Adjust Java version as needed
      architecture: 'x64'

  - script: |
      ./mvnw clean install -B
    displayName: 'Build Spring Boot application'

  - script: |
      ./mvnw test -B
    displayName: 'Run tests'

  - task: PublishBuildArtifacts@0
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/target'
      artifactName: 'spring-boot-app'
      publishLocation: 'Container'
